export const descriptions = {
    tyger:
        "I’m Tyger, a fourth-year software engineering student currently in my last semester of studies. My skills come mostly from what I have learnt in my courses throughout my studies, and from the many projects I have worked on during that time. Technology wise, I have experience in Object Oriented Programming (specifically in Java), UX/UI design, MERN stack applications, and also working in an agile environment. Furthermore, I have industry experience in ReactJS applications and the agile development process.",
    ryan:
        "Hello, I am Ryan Lim and I am a fourth year software engineering student at the University of Auckland. I have experience in full stack development through my project work and internships at various companies. In my previous role, I was involved in Robotic Process Automation (RPA) projects that extracted data from customer’s databases and produced a detailed report on Power BI. I am ready to take on challenges and produce the best results with my team.",
    hideaki:
        "Hi! I am a fourth year software engineering student at the University of Auckland. I have experience in full stack development from personal projects and I also have experience in robotics and embedded systems through my involvement in the university robotics club. I am currently working on a machine learning research project with my project partner Yinhu. I've worked at University as a research student and as an intern in the R&D team at Crown Robotics Technology Centre. My previous work experiences have accustomed me to taking stewardship of projects and working in a team.",
    sam:
        "Hi there! I'm in my final year of a Software Engineering degree at The University of Auckland. I enjoy full stack Web development which I've been learning about in a variety of courses throughout my degree. I've been fortunate enough to have the opportunity to apply my knowledge and interest about web development at my internships. Most recently at Vista Entertainment Solutions I enjoyed working with Angular and .NET Core in a fast paced agile environment. I'm always keen to pick up new technologies and frameworks and apply them to interesting projects.",
    sean:
        "Hi there, I’m Sean Spires. I’m a fourth year software engineer at The University of Auckland. Throughout my degree, I’ve continually developed and refined my technical knowledge of software development. I have a particular interest in back-end development having worked with .NET Core extensively through personal side projects. Alongside this, I’ve also had the privilege of working in industry, interning as both a software developer intern and a  technology consulting intern. These two internships have highlighted to me the importance of combining technological expertise and commercial awareness.",
    josh:
        "Greetings, my name is Joshua Fu. I am a fourth-year software engineering student. I have demonstrated experience in web development and customer service. I am constantly intrigued by the possibilities of technology and how it can improve our daily lives.",
    yinhu:
        "Hello, I am Yinhu Cui. I am a passionate and enthusiastic software developer that is currently studying at the University of Auckland and is efficient with many languages, enjoys working in teams, experienced from internships, always ready to improve, adapt and learn new concepts from anyone including experienced developers. \n I am currently in my final year and the courses that I have taken at university have provided skills and knowledge about algorithms, data structures, complex database queries, database schemata in the industry-standard SQL, design patterns and many languages.My internships at Coda and Clearhead have allowed me to use the learnt knowledge for real life problems such as working on an application to help those with a mental illness.",
    mario:
        "Hello I’m Mario, a software engineering student currently in my last year of study. I have multiple years of experience with software development through academic papers, internships and hackathons. These experiences have enabled me to develop a substantial understanding of the core concepts associated with programming. Additionally, most of my experience has been full-stack (web/mobile) which I have really enjoyed as it allows me to understand all aspects of the projects I work on. \nFurthermore, throughout my time at university and at internships (EY, MYOB) I have always been inclined to take up leadership opportunities.Specifically, leading teams through agile development lifecycles.I personally find it very fulfilling to adjust / adopt agile methodologies to better suit teams’ needs."
};

export default descriptions;
